Fix/BSA-269/Extra Time limit error message
oat-sa/extension-tao-proctoring pull request #857
Opened 2020-10-14 12:38 UTC by shpran

Relates to: [BSA-269](https://oat-sa.atlassian.net/browse/BSA-269)

**Changes:** do not show error if time adjustment increase limit setted to -1.

**How to test:**
1. create the delivery with timed section(s);
2. execute the delivery via TT and pause it via Proctor;
3. refresh the page via Proctor and add Extra Time value which will be greater than consumed time (e.g. if timer was setted to 10 minutes and it was paused on 9:00 - consumed time is 1 minute. So you need to add Extra Time more than 1 minute).

_Previous behaviour: **error message.**_
_Current behaviour: **no error message, extra time has no limits.**_

2020-10-15 09:03 UTC, SergiiTao reviewed
BE looks good :)

2020-10-15 09:03 UTC, SergiiTao approved these changes

2020-10-15 11:32 UTC, bziondik requested changes
Can't reproduce the issue `resource.timeAdjustmentLimits` is `undefined`
Maybe because of different configs?
Please, add migration for extraTime configs

2020-10-15 14:21 UTC, bziondik approved these changes
Please, check if `timeAdjustmentLimits` should be send in case of  `extra_time` mode
- [ ]  New code is covered by tests (if applicable)
- [x]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [x]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

2020-10-16 08:35 UTC, lecosson approved these changes

2020-10-16 08:36 UTC, merged