Feature/pr 470/make delivery logging configurable
oat-sa/extension-tao-proctoring pull request #891
Opened 2021-05-10 15:27 UTC by ks16

Ticket: https://oat-sa.atlassian.net/browse/PR-470

To reduce load on DB added config option which allows to disable delivery logs storing.
Logging is enabled by default. To disable add new option in `taoProctoring/DeliveryLog.conf.php`:
```
return new oat\taoProctoring\model\deliveryLog\implementation\RdsDeliveryLogService(array(
    ... 
    'enable_logging' => false
)); 
```

2021-05-13 07:57 UTC, shpran approved these changes
- [x] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2021-05-20 12:54 UTC, siwane requested changes

2021-05-20 12:54 UTC, siwane commented on scripts/install/RegisterProctoringLog.php
> +            var_dump("CREATING TABLE FAILED");
does this var_dump is required ?

2021-05-20 12:54 UTC, siwane commented on test/integration/deliveryLog/RdsDeliveryLogServiceTest.php
>  }
missing new line

2021-11-24 12:22 UTC, closed without merging